target("libcyclone")
    set_kind("static")
    add_defines("CYC_INSTALL_SLD")
    add_defines("CYC_INSTALL_LIB")
    add_defines("CYC_INSTALL_INC")
    add_defines("CYC_INSTALL_DIR")
    add_defines(""CYC_CC_PROG" ")
    add_includedirs("/usr/local/include")
    add_includedirs("include")
    add_files("runtime.c")
    add_files("dispatch.c")
    add_files("hashset.c")
    add_files("mstreams.c")
    add_files("cyclone.c")
    add_files("gc.c")
    add_files("scheme/*.c")
    add_files("sfri/*.c")
-- add_files("icyc.c")

